@startuml

package "传感器" {
[平层传感器]
[加速度传感器]
[供电监测]
[红外传感器]
}
package "轿顶单元"{
[黑色方形机箱]
[紧急供电电源]
[电源采集板]
[紧急供电电源] -left-> [电源采集板]:备用
}



package "轿厢单元"{
[ARM嵌入式处理器平台]
[显示屏]
}


package "Web智能监控平台"{
[数据传输与聚合]
}
轿厢单元 <|-- [电源采集板]:供电
传感器 <|-- [电源采集板]:供电

[ARM嵌入式处理器平台] --|> Web智能监控平台:数据上行
@enduml