@startuml

package "传感器" {
[平层传感器]
[加速度传感器]
[供电监测]
[红外传感器]
}

传感器 -> 轿顶单元:信号
轿顶单元 -> 轿厢单元:串行数据
轿厢单元 -> Web智能监控平台:网络访问

package "轿顶单元"{
[黑色方形机箱]
[紧急供电电源]
[电源采集板]
}

package "轿厢单元"{
[显示屏]
[ARM主控平台]
}

package "Web智能监控平台"{
[数据传输与信息聚合]
}
@enduml